project:
  name: bee-hive
  path: /Users/bogdan/work/leanvibe-dev/bee-hive
  type: web_application
  primary_language: python
  languages:
    shell: 0.02370791844476055
    python: 0.604551920341394
    html: 0.24561403508771928
    sql: 0.000474158368895211
    typescript: 0.11379800853485064
    css: 0.002844950213371266
    javascript: 0.009009009009009009
  frameworks:
  - FastAPI
  - Pytest
  - Playwright
  - Docker
  - Kubernetes
  file_count: 3225
  line_count: 1472303
  complexity: enterprise
deployment:
  profile: medium
  optimization_level: enterprise
services:
  postgres:
    shared_buffers: 1g
    effective_cache_size: 9GB
    work_mem: 16MB
    maintenance_work_mem: 256MB
    max_connections: 200
    log_statement: none
    log_min_duration_statement: 1000
    extensions:
    - pg_trgm
    - btree_gin
    - vector
    checkpoint_completion_target: 0.9
    wal_buffers: 16MB
    default_statistics_target: 100
  redis:
    maxmemory: 1g
    maxmemory_policy: allkeys-lru
    save:
    - 900 1
    - 300 10
    - 60 10000
    tcp_keepalive: 300
    timeout: 0
    databases: 16
    hash_max_ziplist_entries: 512
    hash_max_ziplist_value: 64
  api:
    memory_limit: 4g
    worker_processes: 4
    worker_connections: 500
    request_timeout: 300
    database_timeout: 120
    search_timeout: 30
    batch_size: 500
    cache_ttl: 300
    enable_compression: true
    cors_enabled: true
  indexer:
    memory_limit: 2g
    concurrent_workers: 8
    batch_size: 500
    index_frequency: 5m
    file_size_limit: 10MB
    ignore_patterns:
    - .git/
    - node_modules/
    - __pycache__/
    - .pytest_cache/
    - venv/
    - .venv/
    - env/
    - .env
    - dist/
    - build/
    - target/
    - .idea/
    - .vscode/
    - coverage/
    - .coverage
    - '*.egg-info/'
    - .tox/
    - .mypy_cache/
    - npm-debug.log*
    - yarn-debug.log*
    - yarn-error.log*
    - .next/
    - .nuxt/
    - out/
    - public/build/
    - '*.pyc'
    - '*.pyo'
    - '*.pyd'
    - __pycache__/
    - .Python
    - build/
    - develop-eggs/
    - downloads/
    - eggs/
    - .eggs/
    - lib/
    - lib64/
    - parts/
    - sdist/
    - var/
    - wheels/
    language_detection: true
    content_extraction: true
    incremental_updates: true
security:
  api_key_length: 64
  password_complexity:
    min_length: 12
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_symbols: true
  encryption_settings:
    algorithm: AES-256-GCM
    key_rotation_days: 30
    encrypt_at_rest: true
  access_control:
    enable_rbac: true
    default_permissions: read
    session_timeout_minutes: 30
  rate_limiting:
    api_requests_per_minute: 500
    search_requests_per_minute: 200
    burst_allowance: 20
  cors_settings:
    allowed_origins:
    - http://localhost:3000
    - http://localhost:8080
    allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    allow_credentials: true
  ssl_settings:
    enabled: true
    min_tls_version: '1.3'
    cipher_suites:
    - ECDHE-RSA-AES256-GCM-SHA384
performance:
  name: Enterprise Scale
  memory_allocation:
    postgres: 4g
    redis: 1g
    api: 4g
    indexer: 2g
  cpu_allocation:
    postgres: 4.0
    redis: 2.0
    api: 4.0
    indexer: 2.0
  connection_limits:
    postgres: 200
    redis: 1000
    api: 500
  cache_settings:
    redis_max_memory: 1g
    postgres_shared_buffers: 1g
    query_cache_size: 5000
  indexing_settings:
    batch_size: 500
    index_frequency: 5m
    concurrent_indexers: 8
  batch_sizes:
    file_processing: 500
    search_results: 500
  timeout_settings:
    api_timeout: 300
    db_timeout: 120
    index_timeout: 3600
features:
  enable_real_time_indexing: true
  enable_search_api: true
  enable_file_monitoring: true
  enable_query_caching: true
  enable_result_caching: true
  enable_compression: true
  enable_ml_analysis: true
  enable_semantic_search: true
  enable_code_intelligence: true
  enable_api_authentication: true
  enable_rate_limiting: true
  enable_audit_logging: true
  enable_metrics: true
  enable_health_checks: true
  enable_performance_monitoring: true
  enable_multi_user: true
  enable_access_control: true
  enable_backup: true
  enable_python_ast_analysis: true
monitoring:
  enabled: true
  metrics:
    enabled: true
    retention_days: 30
    scrape_interval: 30s
    evaluation_interval: 30s
  logging:
    level: INFO
    format: json
    retention_days: 30
  health_checks:
    enabled: true
    interval: 30s
    timeout: 10s
    unhealthy_threshold: 3
  alerts:
    enabled: true
    channels:
    - log
    rules:
    - name: High Memory Usage
      condition: memory_usage > 90
      severity: warning
    - name: API Response Time
      condition: api_response_time > 5000
      severity: warning
    - name: Indexing Errors
      condition: indexing_error_rate > 0.1
      severity: critical
backup:
  enabled: true
  schedule:
    database: 0 2 * * *
    index: 0 3 * * 0
    config: 0 4 * * 0
  retention:
    daily: 7
    weekly: 4
    monthly: 3
  compression: true
  encryption: true
  destinations:
  - local
  verification: true
integrations: {}
