global:
  evaluation_interval: 15s
  scrape_interval: 15s
scrape_configs:
- job_name: project-index-api
  metrics_path: /metrics
  scrape_interval: 30s
  static_configs:
  - targets:
    - project-index-api:8100
