/**
 * TypeScript type definitions for RealWorld Conduit
 * Generated by LeanVibe Agent Hive 2.0 Frontend Specialist
 */

export interface User {
  email: string;
  token?: string;
  username: string;
  bio: string;
  image: string;
}

export interface Profile {
  username: string;
  bio: string;
  image: string;
  following: boolean;
}

export interface Article {
  slug: string;
  title: string;
  description: string;
  body: string;
  tagList: string[];
  createdAt: string;
  updatedAt: string;
  favorited: boolean;
  favoritesCount: number;
  author: Profile;
}

export interface Comment {
  id: number;
  createdAt: string;
  updatedAt: string;
  body: string;
  author: Profile;
}

export interface CreateArticle {
  title: string;
  description: string;
  body: string;
  tagList: string[];
}

export interface CreateComment {
  body: string;
}

export interface LoginCredentials {
  email: string;
  password: string;
}

export interface RegisterCredentials {
  username: string;
  email: string;
  password: string;
}

export interface UpdateUser {
  email?: string;
  username?: string;
  password?: string;
  bio?: string;
  image?: string;
}

export interface ArticlesResponse {
  articles: Article[];
  articlesCount: number;
}

export interface CommentsResponse {
  comments: Comment[];
}

export interface ApiError {
  errors: {
    [key: string]: string[];
  };
}