# Horizontal Pod Autoscalers for LeanVibe Agent Hive
# Enables automatic scaling to support 50+ concurrent agents

---
# HPA for Architecture Agents
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: agent-architect-hpa
  namespace: leanvibe-hive
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agent-architect
  minReplicas: 1
  maxReplicas: 10  # Max architecture agents
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60

---
# HPA for Developer Agents (Higher capacity for development workload)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: agent-developer-hpa
  namespace: leanvibe-hive
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agent-developer
  minReplicas: 2
  maxReplicas: 25  # Highest capacity for development tasks
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30  # Faster scale-up for development
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 20
        periodSeconds: 60

---
# HPA for QA Agents
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: agent-qa-hpa
  namespace: leanvibe-hive
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agent-qa
  minReplicas: 1
  maxReplicas: 15  # QA testing capacity
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 15
        periodSeconds: 60

---
# Meta Agent - No HPA (single instance for coordination)
# Meta agent handles system-wide coordination and doesn't scale horizontally

---
# Vertical Pod Autoscaler for resource optimization
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: agent-developer-vpa
  namespace: leanvibe-hive
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agent-developer
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: agent-developer
      maxAllowed:
        cpu: 1
        memory: 2Gi
      minAllowed:
        cpu: 100m
        memory: 256Mi