/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HiveOpsWebSocketMessages =
  | ConnectionEstablished
  | DashboardInitialized
  | SubscriptionUpdated
  | UpdateMessage
  | ErrorMessage
  | CriticalAlertMessage;

export interface ConnectionEstablished {
  type: "connection_established";
  connection_id?: string;
  subscriptions: string[];
  server_time?: string;
  [k: string]: unknown;
}
export interface DashboardInitialized {
  type: "dashboard_initialized";
  subscriptions: string[];
  connection_info?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface SubscriptionUpdated {
  type: "subscription_updated";
  subscriptions: string[];
  [k: string]: unknown;
}
export interface UpdateMessage {
  type: string;
  subscription: "agents" | "coordination" | "tasks" | "system" | "alerts";
  data: {
    [k: string]: unknown;
  };
  timestamp?: string;
  [k: string]: unknown;
}
export interface ErrorMessage {
  type: "error";
  message: string;
  timestamp?: string;
  [k: string]: unknown;
}
export interface CriticalAlertMessage {
  type: "critical_alert";
  subscription: "alerts";
  data: {
    alerts: {
      [k: string]: unknown;
    }[];
    timestamp?: string;
    [k: string]: unknown;
  };
  timestamp?: string;
  [k: string]: unknown;
}
