# Loki Configuration for LeanVibe Agent Hive Production
# Centralized log aggregation with high performance and retention policies

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://alertmanager:9093

# Frontend for querying
frontend:
  encoding: protobuf

# Limits configuration for production
limits_config:
  # Global limits
  ingestion_rate_mb: 50
  ingestion_burst_size_mb: 100
  max_concurrent_tail_requests: 20
  max_global_streams_per_user: 10000
  max_query_parallelism: 32
  max_streams_per_user: 0
  max_line_size: 256000
  max_entries_limit_per_query: 10000
  max_chunks_per_query: 2000000
  max_query_series: 10000
  
  # Per-user limits
  per_stream_rate_limit: 5MB
  per_stream_rate_limit_burst: 20MB
  
  # Retention policy
  retention_period: 744h  # 31 days
  
  # Query limits
  max_query_time: 12h
  max_query_length: 12000h
  
  # Split queries by interval
  split_queries_by_interval: 30m

# Table manager for retention
table_manager:
  retention_deletes_enabled: true
  retention_period: 744h  # 31 days

# Compactor for log retention
compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

# Analytics and usage statistics
analytics:
  reporting_enabled: false

# Chunk store configuration
chunk_store_config:
  max_look_back_period: 744h  # Must match retention_period

# Storage configuration
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

# Runtime configuration (can be changed without restart)
runtime_config:
  file: /loki/runtime-config.yaml

# Memberlist configuration for clustering (when multiple instances)
memberlist:
  join_members:
    - loki:7946
  dead_node_reclaim_time: 30s
  gossip_interval: 2s
  gossip_nodes: 2
  gossip_to_dead_nodes_time: 30s
  left_ingesters_timeout: 30s
  bind_port: 7946