apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "leanvibe-agent-hive.fullname" . }}
  labels:
    {{- include "leanvibe-agent-hive.labels" . | nindent 4 }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "leanvibe-agent-hive.selectorLabels" . | nindent 6 }}
  {{- with .Values.deployment.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.pod.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "leanvibe-agent-hive.selectorLabels" . | nindent 8 }}
        {{- with .Values.pod.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "leanvibe-agent-hive.serviceAccountName" . }}
      {{- with .Values.pod.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.initContainers }}
      initContainers:
        {{- if .Values.initContainers.databaseMigration.enabled }}
        - name: database-migration
          image: "{{ .Values.initContainers.databaseMigration.image.repository }}:{{ .Values.initContainers.databaseMigration.image.tag | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.initContainers.databaseMigration.image.pullPolicy }}
          command:
            {{- toYaml .Values.initContainers.databaseMigration.command | nindent 12 }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "leanvibe-agent-hive.secretName" . }}
                  key: database-url
          {{- with .Values.initContainers.databaseMigration.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.container.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          {{- if .Values.healthCheck.enabled }}
          {{- with .Values.healthCheck.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.healthCheck.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.healthCheck.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          env:
            # Database configuration
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "leanvibe-agent-hive.secretName" . }}
                  key: database-url
            # Redis configuration
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "leanvibe-agent-hive.secretName" . }}
                  key: redis-url
            # Anthropic API Key
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "leanvibe-agent-hive.secretName" . }}
                  key: anthropic-api-key
            # Application secret key
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "leanvibe-agent-hive.secretName" . }}
                  key: secret-key
            # Kubernetes-specific environment variables
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{- range .Values.container.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "leanvibe-agent-hive.fullname" . }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: var-tmp
              mountPath: /var/tmp
            {{- if .Values.volumes.workspaces.enabled }}
            - name: workspaces
              mountPath: {{ .Values.volumes.workspaces.mountPath }}
            {{- end }}
            {{- if .Values.volumes.logs.enabled }}
            - name: logs
              mountPath: {{ .Values.volumes.logs.mountPath }}
            {{- end }}
            {{- if .Values.volumes.checkpoints.enabled }}
            - name: checkpoints
              mountPath: {{ .Values.volumes.checkpoints.mountPath }}
            {{- end }}
            {{- if .Values.config.create }}
            - name: config
              mountPath: /app/config
              readOnly: true
            {{- end }}
        {{- with .Values.sidecars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 1Gi
        - name: var-tmp
          emptyDir:
            sizeLimit: 1Gi
        {{- if .Values.volumes.workspaces.enabled }}
        - name: workspaces
          persistentVolumeClaim:
            claimName: {{ include "leanvibe-agent-hive.fullname" . }}-workspaces
        {{- end }}
        {{- if .Values.volumes.logs.enabled }}
        - name: logs
          persistentVolumeClaim:
            claimName: {{ include "leanvibe-agent-hive.fullname" . }}-logs
        {{- end }}
        {{- if .Values.volumes.checkpoints.enabled }}
        - name: checkpoints
          persistentVolumeClaim:
            claimName: {{ include "leanvibe-agent-hive.fullname" . }}-checkpoints
        {{- end }}
        {{- if .Values.config.create }}
        - name: config
          configMap:
            name: {{ include "leanvibe-agent-hive.fullname" . }}
            defaultMode: 0644
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.runtimeClassName }}
      runtimeClassName: {{ . }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
      restartPolicy: Always