# Prometheus configuration for LeanVibe Agent Hive 2.0
# Optimized for development and production monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'leanvibe-agent-hive'
    environment: 'development'

# Rules for alerting and recording
rule_files:
  - "alertmanager/rules.yml"
  - "recording_rules.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # FastAPI application metrics
  - job_name: 'leanvibe-api'
    static_configs:
      - targets: ['172.20.0.1:8000']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # PostgreSQL database metrics (using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Redis metrics (using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Docker container metrics (using cAdvisor)
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 20s
    scrape_timeout: 15s

  # Node/system metrics (using node_exporter)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    scrape_timeout: 10s

  # AlertManager self-monitoring
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Custom application metrics endpoints (enabled with enhanced Prometheus exporter)
  - job_name: 'leanvibe-agents'
    static_configs:
      - targets: ['172.20.0.1:8000']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s
    params:
      job: ['agents']

  - job_name: 'leanvibe-workflows'
    static_configs:
      - targets: ['172.20.0.1:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 5s
    params:
      job: ['workflows']

  - job_name: 'leanvibe-performance'
    static_configs:
      - targets: ['172.20.0.1:8000']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s
    params:
      job: ['performance']

  # Dashboard-specific metrics for multi-agent coordination monitoring
  - job_name: 'leanvibe-dashboard-coordination'
    static_configs:
      - targets: ['172.20.0.1:8000']
    scrape_interval: 5s
    metrics_path: /metrics/coordination
    scrape_timeout: 5s
    params:
      format: ['prometheus']

  # Dashboard-specific metrics for performance analytics
  - job_name: 'leanvibe-dashboard-analytics'
    static_configs:
      - targets: ['172.20.0.1:8000']
    scrape_interval: 10s
    metrics_path: /metrics/analytics
    scrape_timeout: 5s
    params:
      format: ['prometheus']

  # Dashboard-specific metrics for security monitoring
  - job_name: 'leanvibe-dashboard-security'
    static_configs:
      - targets: ['172.20.0.1:8000']
    scrape_interval: 15s
    metrics_path: /metrics/security
    scrape_timeout: 10s
    params:
      format: ['prometheus']

  # Dashboard-specific metrics for business intelligence
  - job_name: 'leanvibe-dashboard-business'
    static_configs:
      - targets: ['172.20.0.1:8000']
    scrape_interval: 60s
    metrics_path: /metrics/business
    scrape_timeout: 10s
    params:
      format: ['prometheus']

  # WebSocket connection metrics for real-time dashboard monitoring
  - job_name: 'leanvibe-websockets'
    static_configs:
      - targets: ['172.20.0.1:8000']
    scrape_interval: 10s
    metrics_path: /metrics/websockets
    scrape_timeout: 5s
    params:
      format: ['prometheus']

  # Mobile dashboard performance metrics
  - job_name: 'leanvibe-mobile-dashboard'
    static_configs:
      - targets: ['172.20.0.1:8000']
    scrape_interval: 30s
    metrics_path: /metrics/mobile
    scrape_timeout: 10s
    params:
      format: ['prometheus']

# Remote write configuration (for production)
# remote_write:
#   - url: "https://your-remote-prometheus/api/v1/write"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500

