# Documentation Quality Gates Configuration
# Integration with development workflow to prevent documentation drift

# Quality gate enforcement
enabled: true
minimum_accuracy: 90.0
critical_issue_block: true
port_mismatch_block: true
test_count_drift_threshold: 20

# Auto-correction settings
auto_correction:
  enabled: true
  backup_before_correction: true
  require_approval_for_major_changes: false
  auto_commit_living_docs: true

# Git integration settings
git_integration:
  pre_commit_validation: true
  post_commit_updates: true
  pre_push_comprehensive_check: true
  block_commit_on_critical_issues: true

# CI/CD integration
ci_cd_integration:
  github_actions: true
  documentation_checks: true
  fail_on_accuracy_below_threshold: true
  generate_pr_reports: true
  artifact_upload: true

# Developer experience settings  
developer_experience:
  friendly_error_messages: true
  suggested_fixes: true
  documentation_links: true
  progress_indicators: true
  make_targets: true

# Quality thresholds by check type
quality_thresholds:
  plan_md_minimum: 95.0      # PLAN.md must be very accurate
  prompt_md_minimum: 95.0    # PROMPT.md must be very accurate
  infrastructure_health: 80.0 # Infrastructure health threshold
  living_docs_minimum: 90.0  # Living documentation accuracy
  test_sync_drift_max: 15    # Maximum test count drift allowed

# Validation rules
validation_rules:
  port_accuracy:
    enabled: true
    severity: "critical"
    auto_fix: true
    
  system_state_accuracy:
    enabled: true
    severity: "high" 
    tolerance_percent: 5.0
    
  test_count_accuracy:
    enabled: true
    severity: "medium"
    tolerance_count: 10
    
  completion_percentage:
    enabled: true
    severity: "medium"
    realistic_range: [50, 100]

# Integration points
integrations:
  documentation_validation_system: true
  infrastructure_monitoring_system: true
  test_synchronization_system: true
  living_documentation_framework: true
  consolidation_analyzer: true

# Workflow automation
workflow_automation:
  auto_update_on_code_changes: true
  sync_with_infrastructure_changes: true
  update_test_counts_on_discovery: true
  consolidate_on_major_changes: false

# Reporting and monitoring
reporting:
  generate_daily_reports: false
  generate_on_push: true
  store_historical_accuracy: true
  alert_on_degradation: true
  slack_notifications: false  # Configure webhook if needed
  
# Emergency overrides (use sparingly)
emergency_overrides:
  allow_commit_bypass: true           # git commit --no-verify
  allow_accuracy_override: false     # Override accuracy thresholds
  disable_all_checks: false          # Nuclear option - disable everything