# Living Documentation Framework Configuration
# Automated documentation maintenance preventing accuracy drift

# Framework settings
enabled: true
auto_update_frequency: "on_change"  # Options: "on_change", "hourly", "daily"
validation_threshold: 95.0
backup_before_update: true
git_integration: true

# Template patterns for living content injection
template_patterns:
  system_state: "<!-- LIVING:SYSTEM_STATE -->"
  test_counts: "<!-- LIVING:TEST_COUNTS -->"
  infrastructure: "<!-- LIVING:INFRASTRUCTURE -->"
  performance_metrics: "<!-- LIVING:PERFORMANCE -->"
  agent_capabilities: "<!-- LIVING:AGENTS -->"

# Accuracy validation rules and tolerances
accuracy_rules:
  port_mismatch_tolerance: 0      # No tolerance for port errors
  percentage_tolerance: 5.0       # 5% tolerance for percentages  
  count_tolerance: 10             # 10 item tolerance for counts
  timestamp_staleness_hours: 24   # Hours before content considered stale

# Change detection thresholds
change_thresholds:
  infrastructure_status_change: true      # Any status change triggers update
  test_count_change_minimum: 5           # Minimum test count change to trigger
  functionality_percentage_change: 5.0   # Minimum percentage change to trigger
  performance_degradation_percent: 10.0  # Performance change threshold

# Document update triggers and rules
document_rules:
  PLAN.md:
    update_triggers:
      - infrastructure_change
      - functionality_change  
      - test_count_change
    validation_rules:
      - port_accuracy
      - system_state_accuracy
      - completion_percentage
    update_frequency: "immediate"
    
  PROMPT.md:
    update_triggers:
      - infrastructure_change
      - functionality_change
      - agent_capability_change
    validation_rules:
      - port_accuracy
      - system_state_accuracy
      - agent_count_accuracy
    update_frequency: "immediate"
    
  SYSTEM_CAPABILITY_AUDIT.md:
    update_triggers:
      - test_results_change
      - infrastructure_change
      - performance_change
    validation_rules:
      - test_count_accuracy
      - performance_metrics
      - capability_validation
    update_frequency: "daily"

# Git integration settings
git_hooks:
  pre_commit_validation: true
  post_commit_updates: true
  pre_push_accuracy_check: true
  commit_message_templates: true

# Monitoring and alerting
monitoring:
  continuous_validation: true
  validation_interval_minutes: 30
  accuracy_alert_threshold: 90.0
  critical_issue_immediate_alert: true
  
# Quality gates
quality_gates:
  block_commit_on_accuracy_below: 85.0
  require_manual_approval_below: 90.0
  auto_correction_enabled: true
  auto_correction_backup: true

# Consolidation settings
consolidation:
  detect_duplicate_content: true
  suggest_merge_opportunities: true
  identify_outdated_documents: true
  cleanup_stale_backups_days: 30