apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-tools
  labels:
    app.kubernetes.io/name: leanvibe-agent-hive
    app.kubernetes.io/component: dev-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: leanvibe-agent-hive
      app.kubernetes.io/component: dev-tools
  template:
    metadata:
      labels:
        app.kubernetes.io/name: leanvibe-agent-hive
        app.kubernetes.io/component: dev-tools
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
        - containerPort: 80
          name: http
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin@leanvibe.dev"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "admin"
        - name: PGADMIN_CONFIG_SERVER_MODE
          value: "False"
        volumeMounts:
        - name: pgadmin-data
          mountPath: /var/lib/pgadmin
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      
      - name: redis-commander
        image: rediscommander/redis-commander:latest
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: REDIS_HOSTS
          value: "local:redis:6379:0:dev_password"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      
      volumes:
      - name: pgadmin-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: dev-tools
  labels:
    app.kubernetes.io/name: leanvibe-agent-hive
    app.kubernetes.io/component: dev-tools
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    name: pgadmin
    nodePort: 30080
  - port: 8081
    targetPort: 8081
    name: redis-commander
    nodePort: 30081
  selector:
    app.kubernetes.io/name: leanvibe-agent-hive
    app.kubernetes.io/component: dev-tools