apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: leanvibe-agent-hive-production

# Base configuration
bases:
- ../../base

# Production-specific namespace
namespace: leanvibe-agent-hive-prod

# Production labels
commonLabels:
  environment: production
  tier: production

# Production annotations
commonAnnotations:
  deployment.kubernetes.io/environment: production
  ops.team/contact: "devops@leanvibe.com"
  security.policy/level: "high"

# Production image tags
images:
- name: ghcr.io/leanvibe/agent-hive
  newTag: "v2.0.0-production"

# Production-specific resource scaling
replicas:
- name: leanvibe-api
  count: 5
- name: nginx
  count: 3
- name: postgres
  count: 1
- name: redis
  count: 1

# Production ConfigMap overrides
configMapGenerator:
- name: leanvibe-config
  behavior: merge
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=INFO
  - DEBUG=false
  - WORKERS=6
  - MAX_CONCURRENT_AGENTS=100
  - CORS_ORIGINS=https://app.leanvibe.com,https://dashboard.leanvibe.com
  - METRICS_ENABLED=true
  - MONITORING_ENABLED=true

# Production patches
patches:
# API deployment production optimizations
- target:
    kind: Deployment
    name: leanvibe-api
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "2Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "1000m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "8Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "4000m"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: ENVIRONMENT
        value: production
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: PROMETHEUS_METRICS_ENABLED
        value: "true"

# HPA scaling for production load
- target:
    kind: HorizontalPodAutoscaler
    name: leanvibe-api-hpa
  patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 5
    - op: replace
      path: /spec/maxReplicas
      value: 50
    - op: replace
      path: /spec/metrics/0/resource/target/averageUtilization
      value: 60
    - op: replace
      path: /spec/metrics/1/resource/target/averageUtilization
      value: 70

# PostgreSQL production configuration
- target:
    kind: Deployment
    name: postgres
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "4Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "2000m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "16Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "8000m"

# Redis production configuration
- target:
    kind: Deployment
    name: redis
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "2Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "1000m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "8Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "4000m"

# Production PVC sizes
- target:
    kind: PersistentVolumeClaim
    name: postgres-pvc
  patch: |-
    - op: replace
      path: /spec/resources/requests/storage
      value: "500Gi"
    - op: replace
      path: /spec/storageClassName
      value: "ssd-provisioner"

- target:
    kind: PersistentVolumeClaim
    name: redis-pvc
  patch: |-
    - op: replace
      path: /spec/resources/requests/storage
      value: "100Gi"
    - op: replace
      path: /spec/storageClassName
      value: "ssd-provisioner"

# Production ingress configuration
- target:
    kind: Ingress
    name: leanvibe-ingress
  patch: |-
    - op: add
      path: /metadata/annotations/nginx.ingress.kubernetes.io~1rate-limit-rps
      value: "200"
    - op: add
      path: /metadata/annotations/nginx.ingress.kubernetes.io~1limit-connections
      value: "10"
    - op: add
      path: /metadata/annotations/nginx.ingress.kubernetes.io~1proxy-buffer-size
      value: "16k"
    - op: add
      path: /metadata/annotations/nginx.ingress.kubernetes.io~1proxy-buffers-number
      value: "8"

# Production secrets (to be managed by external-secrets operator)
secretGenerator:
- name: leanvibe-secrets
  behavior: replace
  files:
  - secrets/production.env
  options:
    disableNameSuffixHash: true