name: Lint (Ruff)

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies (minimal)
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Ruff check (app + tests only)
        run: |
          ruff --version
          ruff check app/ tests/
