name: Lint (Ruff)

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies (minimal)
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Get changed Python files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.py

      - name: Ruff check (changed files only)
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          ruff --version
          ruff check $(echo "${{ steps.changed-files.outputs.all_changed_files }}")

      - name: No Python changes detected
        if: steps.changed-files.outputs.all_changed_files == ''
        run: echo "No Python file changes; skipping Ruff."
